### PR TITLE
Reworking the prompt

### PR DESCRIPTION
**Pull request by shiffman**
Adding biographical information and trying to provide better context for the context?

### CODE REVIEW

**Comment by kfahn22** [comment]
I don't think the biographical info is necessary.  There is a Wikipedia page with most of this info, so the model will most likely already know it.   Also, I would tell the model not to use the quotes verbatim. (I created a bot on HuggingFace and added quotes as context and this was a issue.)

**Comment by supercrafter100** [comment]
OpenAI suggests using the quotes in their documentation for providing examples. During previous tests using them it didn't seem to even include them in the response so I'm guessing the model (gpt-4, llama) knows not to include them? I guess it can't hurt having it in the system prompt though.

**Comment by shiffman** [comment]
> I don't think the biographical info is necessary. There is a Wikipedia page with most of this info, so the model will most likely already know it. Also, I would tell the model not to use the quotes verbatim. (I created a bot on HuggingFace and added quotes as context and this was a issue.)

It's not necessary but it's helpful and useful in my experience! I've run simple tests asking information about things like my bio or Nature of Code with and without additional context and the responses are more reliable and focus on the proper references and info with the additional information and context!

**Comment by kfahn22** [comment]
I think you are right that adding background info can help, especially when
it is likely to hallucinate.  Are you planning on asking about his
background?

**Pull request merged**
