### PR TITLE
typescript support , added modules, MOST IMPORTANTLY... IT WORKS

### PR DESCRIPTION
**Pull request by JuggernautJf**
added ts supports along with js
figured out the way to use type: "module"

### CODE REVIEW

**Comment by supercrafter100** [comment]
You appear to have included your node_modules folder?

**Comment by JuggernautJf** [comment]
> You appear to have included your node_modules folder? As well as your dist folder?

thanks added gitignore 👍

**Comment by JuggernautJf** [comment]
Yea This is Good enough for today...

- [ ] added ts and js "seamless" support

- [ ] added SetupFiles command => "bizzaro-devin.createFiles"
-- [ ] adds index.html with boilerPlate
-- [ ] adds sketch.js

**Comment by shiffman** [comment]
Thank you @JuggernautJf for contributing! Wow, I can see you've done a lot of work here! At the moment, this project is less about being a proper VS Code extension and more an odd experiment for a performance coming up in April. So I am not prioritizing things like typescript or proper software engineering principles at this time. For contributing I would suggest opening issues with proposals first and implementing small, incremental changes in pull requests! 

Open to considering the work you have done here of course, and thank you for your efforts and generosity!

**Comment by JuggernautJf** [comment]
HOW TO USE?:
https://github.com/CodingTrain/Bizarro-Devin/assets/142104720/7372c321-d096-4c26-bbd9-b0018a99cf8b

**Comment by JuggernautJf** [comment]
@shiffman How i create file in workspace:
```js
import vscode from 'vscode';

/**
 * Creates a file with the given relative path and optional content.
*
* @param {string} path - The relative path of the file to be created.
* @param {string} [content] - The content to be written to the file. Optional, defaults to an empty string.
* @return {Promise<void>} - A promise that resolves when the file is created successfully.
* @param {boolean} options.show - set true to open file
*/
export default async (path, content = "",options={}) => {
  const activeFolder = vscode.workspace.workspaceFolders?.[0];
  const FilePath = vscode.Uri.joinPath(activeFolder.uri, path);
  const FileContent = new TextEncoder().encode(content);
  await vscode.workspace.fs.writeFile(FilePath, FileContent);
  if (options.show) {
    const document = await vscode.workspace.openTextDocument(FilePath);
    await vscode.window.showTextDocument(document);
  }
};
```

**Pull request closed without merging**
